{% set name = "blosc" %}
{% set version = "1.8.3" %}
{% set sha256 = "e978a58e39a7b4bb4c1a5fb6757c97d3646634adf1cbde6789c7a508912d4dad" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - blosc
    - setuptools
    - wheel
    - scikit-build
  run:
    - python
    - blosc
    - numpy

test:
  requires:
    - numpy
    - psutil
  imports:
    - blosc
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: BSD
  license: BSD 3-Clause
  license_file: LICENSES/PYTHON-BLOSC.txt
  summary: 'A Python wrapper for the extremely fast Blosc compression library'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
    - beckermr
